x-app-base: &app_base
  build:
    context: .
    dockerfile: Dockerfile.dev
  restart: unless-stopped
  tty: true
  volumes:
    - .:/var/www
  networks:
    - dash-network

services:
  web:
    <<: *app_base
    container_name: dash-web
    ports:
      - "8000:8000"
    depends_on:
      - cache

  # queues:
  #   <<: *app_base
  #   container_name: dash-queues
  #   command: [ "php", "artisan", "queue:work" ]
  #   depends_on:
  #     - cache

  # scheduler:
  #   <<: *app_base
  #   container_name: dash-scheduler
  #   command: [ "sh", "-c", "while true; do php artisan schedule:run --verbose --no-interaction & sleep 60; done" ]
  #   depends_on:
  #     - web

  frontend:
    image: node:current-alpine
    container_name: dash-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - dash-network
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: dash-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dash-network

  cache:
    image: redis:7
    container_name: dash-cache
    restart: always
    networks:
      - dash-network

volumes:
  pgdata:


networks:
  dash-network:
    driver: bridge
